version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  admin:
    build:
      context: ./admin
    ports:
      - "5174:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules
