version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=https://lumenera-backend.onrender.com
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  admin:
    build:
      context: ./admin
      args:
        - VITE_BACKEND_URL=https://lumenera-backend.onrender.com
    ports:
      - "5174:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
