pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            agent {
                docker { image 'node:16' }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            agent {
                docker { image 'node:16' }
            }
            steps {
                sh 'NODE_ENV=test npm test'
            }
        }
    }
}
